### ISSUE TITLE
Executables for linux

### ISSUE THREAD

**Issue by siarhei-makarevich** [rokett/Citrix-NetScaler-Exporter#12]
Is there any chance to see linux executables?

I'm not familiar with Go unfortunately, can I build your code on linux environment and receive working executable?
If you provide any steps to do that I would be very grateful.

**Comment by rokett** [comment]
it should be pretty easy....there's nothing which is OS specific as far as I can recall off the top of my head.

Dependencies are all included within the repository, so you should just be able to clone the repo to your linux environment and then `go build`.

It would be handy to have Linux executables as official releases so I'll look at changing the make file to allow that and ensure they're part of the normal release cycle as new versions are released.

**Comment by siarhei-makarevich** [comment]
Thank you 

> go build

worked for me
