### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by albertocastro63** [rokett/Citrix-NetScaler-Exporter#14]
I understand that this question may be out of scope here but if someone know of an existing Grafana dashboard for this exporter it would make my life a lot simpler. I looked into the Grafana labs website and I could not find anything. Thanks.

**Comment by rokett** [comment]
We have built a few dashboards based on this data....I'll take a look when I'm at work next week about exporting and adding them to the repository as an example.

**Comment by albertocastro63** [comment]
Thank you very much.

**Comment by rokett** [comment]
Added example dashboards

**Comment by albertocastro63** [comment]
Thank you.
