### ISSUE TITLE
Error while building the executable

### ISSUE THREAD

**Issue by sanket4373** [rokett/Citrix-NetScaler-Exporter#2]
I want to use your project for doing Netscaler monitoring. I am seeing this package dependency issue while trying to build your project. 
```
:~/go/src/github.com/Citrix-NetScaler-Exporter$ go build
main.go:4:2: cannot find package "Citrix-NetScaler-Exporter/netscaler" in any of:
	/home/go/src/github.com/Citrix-NetScaler-Exporter/vendor/Citrix-NetScaler-Exporter/netscaler (vendor tree)
	/usr/local/go/src/Citrix-NetScaler-Exporter/netscaler (from $GOROOT)
	/home/go/src/Citrix-NetScaler-Exporter/netscaler (from $GOPATH)
```

I think something is missing here.. this doesn't look like a correct path `/usr/local/go/src/Citrix-NetScaler-Exporter/netscaler` .  I did tried using the dependency package `dep ensure` to install the missing package. But I guess path should've been inside `github.com`, something like this: `/usr/local/go/src/Citrix-NetScaler-Exporter/netscaler`.  

I just followed the instructions from the README to build the executable. Kindly let me know if I am missing something here.

**Comment by rokett** [comment]
Hi,

unfortunately I haven't tested building it on a Linux machine as we tend to use Windows in our organisation.  It shouldn't make a difference mind you; none of the packages are reliant on Windows as far as I know.

My folder structure looks like this:

````
C drive
    - Development
        - Go
            - Src
                - Citrix-NetScaler-Exporter
````

My GOPATH environment variable is set to `C:\Development\Go`.  Could it just be that Go is expecting to find the main `Citrix-NetScaler-Exporter` folder directly in `Src` and you have it nested in a different folder?  Maybe I'm doing it wrong and should fully qualify the import path...I'm not 100% sure as I'm no Go expert,

**Comment by meesameesa** [comment]
@sanket4373 move the Citirx-NetScaler-Exporter clone to `/home/go/src/` and run the build from there. Worked fine for me on Linux.

**Comment by sanket4373** [comment]
@meesameesa @rokett: That worked. Changed the path and cloned the repo to `home/go/src` . However, IMHO it should be under `home/go/src/github.com` if I am not wrong.

**Comment by rokett** [comment]
What would be normal practice for Go applications?

**Comment by rokett** [comment]
Have double checked and @sanket4373 is correct in that I had the path wrong.  I've amended it now to match normal Go practices.
