### ISSUE TITLE
Timeout error while connecting to the Netscaler 

### ISSUE THREAD

**Issue by sanket4373** [rokett/Citrix-NetScaler-Exporter#3]
I was able to run the executable on my linux machine. Next, I am running prometheus locally on the UI running on : `localhost:9090`, On the UI when I go to Status > Target and refresh the page to connection for the executable which is running on my terminal gets dropped.

This is the error I am getting on my terminal:

```
./Citrix-NetScaler-Exporter -url http://xxx.xxx.xxx.xxx/menu -username stats -password "xxxxxx"
level=info ts=2017-10-12T20:34:25.805279423Z caller=main.go:1986 app=Citrix-NetScaler-Exporter bind_port=9280 url=http://xxx.xxx.xxx.xxx/menu version=v build= msg="Listening on port :9280"
level=error ts=2017-10-12T20:34:48.16445661Z caller=main.go:1643 app=Citrix-NetScaler-Exporter bind_port=9280 url=http://xxx.xxx.xxx.xxx/menu/ version=v build= msg="error sending request: Post http://xxx.xxx.xxx.xxx/menu/nitro/v1/config/login: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```
And here is the snippet of Prometheus UI running locally.

<img width="1440" alt="screen shot 2017-10-12 at 3 56 20 pm" src="https://user-images.githubusercontent.com/8472485/31518767-e9124994-af65-11e7-86b1-8ac15bde98a4.png">

Has anyone seen this error? Am i missing something here?

**Comment by sanket4373** [comment]
Also, Is there a way for me to verify that I am collecting the metrics from the Netscaler inside my exporter itself? Because I should first know that I am even getting connected to the Netscaler and the metrics are being pulled to it. Thanks!

**Comment by rokett** [comment]
Your first problem is the url you're passing to it; you shouldn't add the `/menu` to the end as that makes the API call invalid.

Once it's running you can browse to `http://localhost:9280/metrics` to see what it has pulled from the NetScaler.  Be aware that it may take a few seconds to load that page as it has to connect to the NetScaler and pull all of the stats back when the `metrics` endpoint is requested.

**Comment by sanket4373** [comment]
@rokett: So what you are suggesting that the NetScaler management interface URL is something which should be something like this:

 `./Citrix-NetScaler-Exporter -url http://xxx.xxx.xxx.xxx -username stats -password "xxxxxx"` ?

**Comment by sanket4373** [comment]
Nevertheless I am still getting the same error: 
`level=error ts=2017-10-12T20:34:48.16445661Z caller=main.go:1643 app=Citrix-NetScaler-Exporter bind_port=9280 url=http://xxx.xxx.xxx.xxx version=v build= msg="error sending request: Post http://xxx.xxx.xxx.xxx/nitro/v1/config/login: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
`

**Comment by rokett** [comment]
I would start with verifying that you can connect to the API properly outside of the exporter.  The Nitro API docs are at https://docs.citrix.com/ko-kr/netscaler/11/nitro-api/nitro-rest/nitro-rest-connecting.html.

Ensure that works, as it seems like the exporter can't connect for some reason, and then come back to the exporter.

**Comment by sanket4373** [comment]
@rokett: Got that working, so apparently I was using the public IP of Netscaler which is used to access the GUI, instead I was supposed to use the Netscaler Private IP to authenticate against it. Got the hint from your last comment and figured that you are using `Nitro API` here to communicate with the Netscaler. I was confused by the name `NetScaler management interface URL` mentioned in the README.

**Comment by rokett** [comment]
Interestingly for us the IP to access the API is the same as that used to access the management console (the NSIP).

There are obviously other ways of setting it up.  Either way I'm happy it's working for you.
