### ISSUE TITLE
Add label for state

### ISSUE THREAD

**Issue by alex48151623** [rokett/Citrix-NetScaler-Exporter#37]
Can a label be added to the metrics for enabled/disabled?

We want to exclude Disabled Virtual Servers, etc, in alerting.

**Comment by alex48151623** [comment]
Turns out this already exists.

**Comment by alex48151623** [comment]
Reopening as the State metric doesn't exist for LB Virtual Servers

**Comment by alex48151623** [comment]
And Enabled/Disabled state would be helpful

**Comment by alex48151623** [comment]
Bump :) this would be useful if you have time, probably as it's own metric, but a label on the existing metrics would work also if easier.

**Comment by rokett** [comment]
State metric added for LBVS and GSLB VS.

**Comment by rokett** [comment]
v4.4.0 is the release you want for this :-)
