### ISSUE TITLE
Possibility to accept self-signed certificates on connection. 

### ISSUE THREAD

**Issue by b13n1u** [rokett/Citrix-NetScaler-Exporter#5]
It would be great if there would be an option to accept self signed certificates.
I guess it is a  default of the go lib to not allow self signed certs.  I would really like to contribute 
a PR but unfortunately I'm not very proficient with golang :(

**Comment by rokett** [comment]
This is possible, but obviously ignoring certificate errors should be used with care and at your own risk.

I've created a branch (**accept-self-signed-certs**) with these changes, use the `--ignore-cert` flag to ignore certificate errors.  This will ignore any and all certificate errors though. 

I don't have any way of testing it as none of our NetScalers use self-signed certs.  Are you able to pull the branch down, build the exe, and test it?

**Comment by b13n1u** [comment]
Thanks! I will give it a try and let you know.

**Comment by b13n1u** [comment]
I have build the branch and everything works perfectly fine. 
No more: 
```
x509: certificate signed by unknown authority"
```

And I get all the metrics properly. 
Many, many thanks!!!

**Comment by rokett** [comment]
great 😃 

I've merged those changes and released a new build (v3.1.0)
