### ISSUE TITLE
Metrics are 0 in exporter when have actual value in citrix adc

### ISSUE THREAD

**Issue by heyoheyo** [rokett/Citrix-NetScaler-Exporter#50]
Hi,

Thank you for a great exporter! I am currently getting 0 for a lot of metrics (e.g. current client connections) for individual servers/virtual servers etc. In the Citrix console I can see that the metrics are not 0, e.g 16 current connections. (anything to do with health/status is working fine and as expected, anything to do with number of connections or similar for individual services is not showing correct data).

Can you tell me if I need to either extend/reduce the frequency in which I pull the metrics or is there anything on the Citrix' side that I need to enable?

Thank you!

**Comment by rokett** [comment]
Closing this now
